#!/usr/bin/env python

import websockets
from websockets.sync.client import connect
import json
import asyncio

async def hello():
    uri1 = "ws://localhost:8765"
    async with websockets.connect(uri1) as websocket:
        name = "ESP2"
        Identification = json.dumps({"name": 'ESP2'})
        await websocket.send(Identification)
        print(f"sent to server: {Identification}")
        response = await websocket.recv()
        data = json.loads(response)
        print("Recieved from Server: ", data)

if __name__ == "__main__":
    asyncio.run(hello())

# if __name__ == "__main__":
#     for _ in range(5):  # Loop to run the function 5 times
#         hello()
